In [1]:
import numpy as np

In [2]:
scores = [3,4,5,6,7]

## to use numpy use as(alias) np.array

In [3]:
numbers =np.array ([3,4,5,6,7])

In [4]:
type(scores)

list

In [5]:
type(numbers)

numpy.ndarray

In [6]:
scores_ = []
for num in scores:
    scores_.append(num*10)
print(scores_)

[30, 40, 50, 60, 70]


### A list can tae multiple data type

In [7]:
age = [12,67,'gh']

In [8]:
age = np.array([12,67,'gh']) #NUmpy array can only be of a single data type

In [9]:
age

array(['12', '67', 'gh'], dtype='<U11')

In [10]:
weights = np.array([45,23,32], dtype=float) # the float specifics the particular data type to be inputed

In [11]:
weights

array([45., 23., 32.])

In [12]:
weights = np.array([45,23,32], dtype=int)

In [13]:
weights

array([45, 23, 32])

In [14]:
age.ndim ## check the dimension

1

## TWO DIMENSIONSAL ARRAY

In [15]:
type(weights)

numpy.ndarray

In [16]:
x =np.array([[2,3,4,5],[2,4,6,8]])

In [17]:
x

array([[2, 3, 4, 5],
       [2, 4, 6, 8]])

In [18]:
x.ndim

2

In [19]:
x.shape

(2, 4)

In [20]:
y = np.array ([[6,4,5,6],[4,5,6,7],[4,5,6,7]])

In [21]:
y

array([[6, 4, 5, 6],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [22]:
y.ndim

2

In [23]:
y.shape

(3, 4)

In [24]:
a = np.array ([[[1,5,6,7],[8,6,6,8],[4,7,5,4]]])

In [25]:
a

array([[[1, 5, 6, 7],
        [8, 6, 6, 8],
        [4, 7, 5, 4]]])

In [26]:
a.ndim

3

In [27]:
a.shape

(1, 3, 4)

In [28]:
v= np.array ([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])

In [29]:
v

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [30]:
v.ndim

2

In [31]:
v.shape

(4, 3)

In [32]:
scores = np.array([3,4,5,6])

In [33]:
len(scores) #length of value

4

In [34]:
scores.size

4

In [35]:
type(scores)

numpy.ndarray

In [36]:
scores.dtype

dtype('int32')

In [37]:
scores = scores.astype ('int') # you can change the data type to either float or integer

In [38]:
scores

array([3, 4, 5, 6])

In [39]:
scores [0]

3

In [40]:
scores [-1]

6

In [41]:
scores [1:3]

array([4, 5])

## Indicing / slicing

In [42]:
x = np.array ([[2,3,4,5], [2,4,6,8]])

In [43]:
x[0] # this extracts the first set or first column

array([2, 3, 4, 5])

In [44]:
x[1]

array([2, 4, 6, 8])

In [45]:
x[0,0] # this extracts the first column series and the first number in the column

2

In [46]:
x[0,-1]

5

In [47]:
x[1,-1]

8

In [48]:
x[1,-3]

4

In [49]:
x[:,2] # the colon extracts more than one sets /column

array([4, 6])

In [50]:
x[:,1:3] # this is to extract two numbers from two different columns e.g 3 & 4  from the first colun and 4 & 6 from the second row

array([[3, 4],
       [4, 6]])

## Boolean Indexing

In [51]:
x[x > 2] # a command that extracts from array of numbers greater than two

array([3, 4, 5, 4, 6, 8])

In [52]:
x[x <= 5] # a command that extracts from array of numbers lesser tham or equal to 5

array([2, 3, 4, 5, 2, 4])

In [53]:
x_subset = x [x > 2]

In [54]:
x_subset # it performs the same function as the previous code

array([3, 4, 5, 4, 6, 8])

In [55]:
x_subset = x_subset.reshape(2,3) # it changes the shape of the set or array of numbers

In [56]:
x_subset

array([[3, 4, 5],
       [4, 6, 8]])

In [57]:
x_subset = x_subset.reshape(3,2)

In [58]:
x_subset

array([[3, 4],
       [5, 4],
       [6, 8]])

## Vectorized Operation

In [59]:
x = x*5 # scalar Multiplication (it multiples all values in array by 5)

In [60]:
x

array([[10, 15, 20, 25],
       [10, 20, 30, 40]])

In [61]:
test_score = np.array ([10,21,19,23])

In [62]:
exam_score = np.array([24,56,45,68])

In [63]:
total_scores = np.array (test_score + exam_score)

In [64]:
total_scores

array([34, 77, 64, 91])

In [65]:
mean = np.mean(total_scores) #mean

In [66]:
np.median(total_scores) # median

70.5

In [67]:
np.std (total_scores) # standard deviation

21.0535032714273

In [93]:
np.var (total_scores) # variance

443.25

## Pandas

# Panda is a moduule that easily works with datasets => DATA Structure => series and Data Frames

In [69]:
import pandas as pd

#from pandas import Series, DataFrames (to import datastructure from panda)

In [70]:
names = pd.Series(['Jane', 'Jacob' , 'Chibuzor' , 'Cynthia' , 'Mo' , 'Zita']) # Series is spelt in capital Letter S

In [71]:
type(names)

pandas.core.series.Series

In [72]:
names

0        Jane
1       Jacob
2    Chibuzor
3     Cynthia
4          Mo
5        Zita
dtype: object

In [73]:
scores = pd.Series([66,34,12,45,78], index=['a','b','c','d','e']) # index are also known as labels in pandas

In [74]:
scores

a    66
b    34
c    12
d    45
e    78
dtype: int64

In [75]:
scores['d']

45

In [76]:
scores['e']

78

In [77]:
scores['a':'c']

a    66
b    34
c    12
dtype: int64

In [78]:
names[0:3] # series are one dimensional

0        Jane
1       Jacob
2    Chibuzor
dtype: object

In [79]:
names = pd.Series(['Tolu','Lola', 'John', 'Jude', 'Mary'], index=['a', 'b','c', 'd','e'])

In [80]:
df = pd.DataFrame({'Names' : names, 'Scores' : scores ,}) # use set brackets

In [81]:
df # DataFrames

Names  Scores
a  Tolu      66
b  Lola      34
c  John      12
d  Jude      45
e  Mary      78

In [82]:
week = pd.Series (['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'], index=['a', 'b','c', 'd','e','f','g'])

In [83]:
food = pd.Series (['Jollof Rice', 'Yam' , 'Sphag', 'Bread' , 'Swallow', 'fiesta rice', 'Beans'], index=['a','b','c','d','e','f','g'])

In [84]:
df = pd.DataFrame({'Days_Of_the_week': week, 'Fav_Food': food})

In [85]:
df

Days_Of_the_week     Fav_Food
a           Sunday  Jollof Rice
b           Monday          Yam
c          Tuesday        Sphag
d        Wednesday        Bread
e         Thursday      Swallow
f           Friday  fiesta rice
g         Saturday        Beans

## Wlrking with real world  data

In [86]:
import pandas as pd

In [87]:
data = pd.read_csv(r"C:\Users\WIMBIZ\Documents\Data_Analysis_with_python\Data_Sheet_Udemy_Courses_-_Music_Courses - Data_Sheet_Udemy_Courses_-_Music_Courses.csv")

In [88]:
data

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

In [89]:
type(data)

pandas.core.frame.DataFrame

In [94]:
data = pd.read_excel('C:/Users/WIMBIZ/Documents/Data_Sheet_Udemy_Courses_-_Music_Courses.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/WIMBIZ/Documents/Data_Sheet_Udemy_Courses_-_Music_Courses.xlsx'

## Data Exploration

## Head Method is used to extract first 5 rows by default from a data

In [95]:
data.head()

course_id                                       course_title  \
0      19421              Free Beginner Electric Guitar Lessons   
1     238934  Pianoforall - Incredible New Way To Learn Pian...   
2      41884                Getting Started with Playing Guitar   
3      42271      Complete Guitar System - Beginner to Advanced   
4      26956                            Learn Guitar in 21 Days   

                                                 url  price  num_subscribers  \
0  https://www.udemy.com/beginner-electric-guitar...      0           101154   
1  https://www.udemy.com/pianoforall-incredible-n...    200            75499   
2  https://www.udemy.com/getting-started-with-pla...      0            47652   
3  https://www.udemy.com/complete-guitar-system-b...    145            32935   
4     https://www.udemy.com/learn-guitar-in-21-days/     20            26504   

   num_reviews  num_lectures           level  Rating  content_duration  \
0         1042            95      All Levels    0.88               4.5   
1         7676           362  Beginner Level    0.96              30.0   
2         1141            26      All Levels    0.68               4.0   
3         2713           310      All Levels    0.65              34.0   
4          192            82      All Levels    0.41               2.5   

    published_timestamp              subject  
0  2012-06-15T17:00:33Z  Musical Instruments  
1  2014-08-07T06:27:51Z  Musical Instruments  
2  2013-05-29T15:28:07Z  Musical Instruments  
3  2013-05-29T15:24:47Z  Musical Instruments  
4  2012-10-21T20:36:50Z  Musical Instruments

In [ ]:
data.head(10) ## the number specifies the numbers of row to be extracted

In [ ]:
data.tail() # extracts the last 5 rows from the dataset

In [ ]:
data.info() # extracts the info in the columns and the datatype

In [ ]:
data.shape # is a property in jupyter

In [ ]:
data.columns

## Filtering, Slicing, Indexing

In [ ]:
data

In [ ]:
data['url'] # pandas in series

In [ ]:
data[['url']] #pandas in DataFrames

In [ ]:
data[['course_title']]

## loc / label Selection

In [ ]:
data.loc [:5, 'course_title'] # the lock function locks a specific column or row

In [ ]:
data.loc [0:20, ['course_title']].head()

In [ ]:
data.loc [0:50, 'url']

In [ ]:
data.loc [0:50, ['url']]

In [ ]:
data [['course_title', 'num_lectures']] # to run this code it has to be in DataFrames or it automatically reads erroe

In [ ]:
data.loc[:5, ['course_title', 'num_lectures']] # to lock and extract from row 0-5 in both columns

In [ ]:
data.loc[0, 'course_title']

In [ ]:
data.loc[:10, ['url' ,'price']]

In [ ]:
data.loc[:10, 'course_id' : 'num_reviews'] ## you don't have to use extra square bracket because you are importing a large data

In [ ]:
data.iloc[:10, [0]] it extracrs the index on the column as it is (e.g 0-2) will print exactly that unlike loc

In [ ]:
data.iloc[:5, 0:3] the right number is the column and it uses a plus one (+1) index

In [ ]:
# Conditional Selection

data.subject == 'Musical Instruments'

len(data[data.subject == 'Musical Instruments']) # this checks the length in data using data subject where the value is equal to Musical Instruments

In [ ]:
# this is to merge two conditions together the AND symbol is & and OR symbol is | backslash

data.loc[(data.price > 100) & (data.level == 'Beginner Level'), ['price', 'url', 'course_id']].head()
 ## data.price specifies the specific column

In [ ]:
##class work check for data level to check the beginner level

len(data.loc[data.level =='Beginner Level']) ## adding len to is the length of the data with beginner level

### Data Cleaning

In [ ]:
data.isnull # extracts the null data from the dataset

In [ ]:
data.isnull().sum() # sums up all extracted null datas from dataset

In [ ]:
data.duplicated() # extracts duplicated data

In [ ]:
data.duplicated().sum() # sums up the extracted duplicated data

# Dealing with null values
- Replacment
- Drop

In [ ]:
data.copy = data.copy() ## Copies the data set

data.drop('course_id', axis =1, inplace=True) # drops the null values and inplace+True is import

In [ ]:
dat

In [ ]:
data.describe() # Does statistics on all numerical data in thr datasets

### Replacements

In [ ]:
# SSOT

data. price.fillina (data.price.mean(),inplace=True) # Filina fills the null values / replace them

In [97]:
data.price.mean() ## checks the mean for the data

49.55882352941177

In [98]:
data.price.fillna(method='bfill', inplace=True)

C:\Users\WIMBIZ\AppData\Local\Temp\ipykernel_16388\2396842106.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.price.fillna(method='bfill', inplace=True)
C:\Users\WIMBIZ\AppData\Local\Temp\ipykernel_16388\2396842106.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.price.fillna(method='bfill', inplace=True)


In [92]:
data.price.bfill(inplace=True) # A better to use the formula without warnings

C:\Users\WIMBIZ\AppData\Local\Temp\ipykernel_16388\1850500474.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.price.bfill(inplace=True) # A better to use the formula without warnings


In [ ]:
data.head()

In [ ]:
data['level'].value_counts() #checks all category in level

In [ ]:
data['course_title'].value_counts()

In [ ]:
data['level'].replace({'Expert Level': 'Advanced Level'}, inplace=True)

In [ ]:
#second optiom to replace

data['level']= data['level'].replace ({'Expert Level' : 'Advanced Level'})

In [ ]:
data['level'].value_counts()

## Drop

In [ ]:
data.dropna(axis=0, inplace=True) ## dropna is used for rows replacements

In [ ]:
#To drop a row if all values are null

data.dropna(axis=0, inplace=True, how ='all')

In [ ]:
data.dropna(axis=1, inplace=True, how ='all')

In [ ]:
data.drop_duplicates # chcks for duplicated rows

In [ ]:
data.info()

In [ ]:
data.price =data.price.astype('str') #to change the data format

In [ ]:
data['price'] = 'N' +  " " + data['price'] #to add Naira sign to the price values

In [ ]:
data .copy

In [ ]:
data.info()

In [ ]:
# this removes the Naira sign and removes str as the d datatype and retirns it to the original data
data['price'] = data['price'].str.replace ('N N', " ")

In [ ]:
data

In [ ]:
data.copy

In [99]:
data

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

In [ ]:
data .to_csv ("cleaned Data.csv")